version: "3"
services:
  app:
    build: .
    command: make test
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./oAuthHelpers/:/go/src/app/oAuthHelpers/
      - ./oAuthMiddleware/:/go/src/app/oAuthMiddleware/
      - ./test/:/go/src/app/test/
      - ./Makefile:/go/src/app/Makefile

